# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: >
  What The Mac?!
email: g.r.pugh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Graham Pugh's rarely-updated blog about Mac Admin-related stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grahampugh.github.io" # the base hostname & protocol for your site
src_url: "https://github.com/grahampugh/grahampugh.github.io/blob/master"
# twitter_username: GrahamRPugh
github_username: grahampugh
slack_username: grahamrpugh
mastodon_server: mas.to
mastodon_username: "@SubjectMac"
author: grahampugh
timezone: Europe/Zurich
future: true

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

#pagination
plugins:
  - jekyll-gist
  - jekyll-paginate
paginate: 10
paginate_path: "/page/:num"
